# Ports: 
# 6273 - Immerse HTTP
# 6274 - HeavyDB - TCP Port
# 6275 - HeavyIQ - HTTP
# 6278 - HeavyDB - backend http port
# 6279 - HeavyDB - Calcite


version: '3.8'

services:
  heavydb:
    container_name: heavyaiserver
    image: docker-internal.mapd.com/mapd/mapd-render:master
    restart: always
    ipc: shareable
    entrypoint: /bin/bash -c '/opt/heavyai/bin/heavydb --config /var/lib/heavyai/heavy.conf'
    volumes:
    - /var/lib/heavyai:/var/lib/heavyai
    networks:
    - heavy-network
    ports:
    - "6274:6274"
    - "6278:6278"

  immerse:
    container_name: immerse
    image: docker-internal.mapd.com/mapd/mapd-render:master
    restart: always
    ipc: shareable
    entrypoint: /bin/bash -c '/opt/heavyai/bin/heavy_web_server --config /var/lib/heavyai/immerse/heavy.conf'
    volumes:
    - /var/lib/heavyai:/var/lib/heavyai
    networks:
    - heavy-network
    ports:
    - "6273:6273"

  iq:
    container_name: iq
    image: docker-internal.mapd.com/mapd/mapd-render:master
    restart: no
    ipc: shareable
    environment:
    - CONFIG_FILE=/var/lib/heavyai/iq/heavy.conf
    - MAPD_DATA=/var/lib/heavyai/iq
    - MAPD_HEAVYIQ_PORT=6275
    entrypoint: /bin/bash -c '/opt/heavyai/scripts/ee/start_heavyiq.sh'
    volumes:
    - /var/lib/heavyai:/var/lib/heavyai
    networks:
    - heavy-network
    ports:
    - "6275:6275"

networks:
  heavy-network:
    name: heavy-network
