

services:
  heavydb:
    container_name: {{HEAVYDB_SERVICE_NAME}}
    image: {{CONTAINER}}
    restart: unless-stopped
    ipc: shareable
    volumes:
    - /var/lib/heavyai:/var/lib/heavyai
    networks:
    - heavy-network
    ports:
    - "{{HEAVYDB_PORT}}:{{HEAVYDB_PORT}}"
    - "{{HEAVYDB_BACKEND_PORT}}:{{HEAVYDB_BACKEND_PORT}}"
    - "{{IMMERSE_PORT}}:{{IMMERSE_PORT}}"
    - "{{HEAVYIQ_PORT}}:{{HEAVYIQ_PORT}}"
    
  deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  heavy-network:
    name: heavy-network
