version: '3.8'

services:
  vllm:
    container_name: vllm
    image: vllm/vllm-openai:latest
    command:
      - --model=heavyai/heavyiq-llama-3-70b-16k-combo-v61-5-no-cte-judge-3584-tokens-lora-r-512-a-1024-lr-1-1e-5
      - --trust-remote-code
      - --max-num-batched-tokens=16384
      - --enable-prefix-caching
      - --max-model-len=16384
      - --dtype=bfloat16
      - --port=5000
      - --tensor-parallel-size=8 #can be used for parallel usage across GPU's
    runtime: nvidia
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=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
    ports:
      - "5000:5000"
    ipc: host

  embeddings:
    container_name: embeddings
    image: ghcr.io/huggingface/text-embeddings-inference:1.3.0
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['6']
              capabilities: [gpu]
    ports:
      - "5001:80"
    volumes:
      - ./embeddings_data:/data
    command: [
      "--model-id", "Alibaba-NLP/gte-large-en-v1.5",
      "--revision", "main"
    ]

  whisper:
    container_name: whisper
    image: whisper_server
    ports:
      - "5002:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['7']
              capabilities: [gpu]
    runtime: nvidia
