

services:
  heavydb:
    container_name: {{HEAVYDB_SERVICE_NAME}}
    image: {{CONTAINER}}
    restart: always
    ipc: shareable
    entrypoint: /bin/bash -c '/opt/heavyai/bin/heavydb --config {{HEAVYDB_CONFIG_LOCATION}}'
    volumes:
    - /var/lib/heavyai:/var/lib/heavyai
    networks:
    - heavy-network
    ports:
    - "{{HEAVYDB_PORT}}:{{HEAVYDB_PORT}}"
    - "{{HEAVYDB_BACKEND_PORT}}:{{HEAVYDB_BACKEND_PORT}}"
    - "{{IMMERSE_PORT}}:{{IMMERSE_PORT}}"
    - "{{HEAVYIQ_PORT}}:{{HEAVYIQ_PORT}}"


networks:
  heavy-network:
    name: heavy-network
